language: python
services:
  - docker
python:
  - "3.8"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
  - make test_xunit
services:
  -docker
deploy:
  provider: heroku
  app: boiling-stream-22946
  api_key: ${HEROKU_API_KEY}
